# Generated by Django 4.1.4 on 2023-04-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='humans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.TimeField()),
                ('Date', models.DateField()),
                ('Total_Females', models.IntegerField()),
                ('Total_Males', models.IntegerField()),
                ('Total_attracted_humans', models.IntegerField()),
                ('Total_present_humans', models.IntegerField()),
            ],
        ),
    ]
